/*
 * This file is generated from insns.dat, regs.dat and token.dat
 * by tokhash.pl; do not edit.
 */

#include "compiler.h"
#include <string.h>
#include "nasm.h"
#include "hashtbl.h"
#include "insns.h"

struct tokendata {
    const char *string;
    int16_t tokentype;
    int16_t aux;
    int32_t num;
};

int nasm_token_hash(const char *token, struct tokenval *tv)
{
#define UNUSED 16383
    static const int16_t hash1[2048] = {
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        906,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        765,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        948,
        509,
        0,
        375,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        252,
        -2219,
        1132,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        -328,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        -1265,
        1066,
        0,
        UNUSED,
        0,
        0,
        78,
        0,
        -369,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -4,
        UNUSED,
        UNUSED,
        197,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        -193,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        304,
        553,
        0,
        UNUSED,
        954,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        -1879,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        2638,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -1934,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        811,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        1808,
        0,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        1568,
        UNUSED,
        UNUSED,
        UNUSED,
        -44,
        UNUSED,
        UNUSED,
        355,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        803,
        UNUSED,
        UNUSED,
        983,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        0,
        559,
        362,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1065,
        0,
        UNUSED,
        -802,
        0,
        1468,
        103,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        1750,
        184,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -1709,
        1205,
        UNUSED,
        UNUSED,
        UNUSED,
        760,
        239,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        -190,
        UNUSED,
        UNUSED,
        UNUSED,
        566,
        UNUSED,
        0,
        UNUSED,
        0,
        550,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        -311,
        0,
        0,
        UNUSED,
        0,
        0,
        971,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        1087,
        UNUSED,
        178,
        0,
        0,
        UNUSED,
        0,
        763,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        1179,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        119,
        1377,
        -275,
        UNUSED,
        105,
        UNUSED,
        22,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1189,
        0,
        UNUSED,
        0,
        215,
        UNUSED,
        970,
        UNUSED,
        16,
        -1843,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1104,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        -249,
        UNUSED,
        UNUSED,
        UNUSED,
        1351,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        1399,
        UNUSED,
        UNUSED,
        70,
        1257,
        UNUSED,
        0,
        UNUSED,
        75,
        1454,
        1397,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        1975,
        0,
        UNUSED,
        1178,
        0,
        0,
        0,
        0,
        0,
        0,
        UNUSED,
        1498,
        46,
        UNUSED,
        0,
        -334,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        808,
        UNUSED,
        0,
        1251,
        UNUSED,
        96,
        UNUSED,
        UNUSED,
        -431,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        272,
        0,
        0,
        464,
        -1893,
        1927,
        -739,
        847,
        0,
        0,
        1443,
        UNUSED,
        0,
        0,
        -356,
        UNUSED,
        321,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        713,
        457,
        -913,
        1001,
        1897,
        UNUSED,
        0,
        26,
        707,
        UNUSED,
        1335,
        0,
        1153,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        325,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        343,
        922,
        0,
        -378,
        450,
        806,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1162,
        415,
        UNUSED,
        UNUSED,
        -869,
        UNUSED,
        UNUSED,
        UNUSED,
        1465,
        UNUSED,
        763,
        998,
        UNUSED,
        -653,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        911,
        2021,
        UNUSED,
        UNUSED,
        -43,
        UNUSED,
        UNUSED,
        629,
        884,
        1547,
        2549,
        1191,
        UNUSED,
        0,
        UNUSED,
        0,
        205,
        UNUSED,
        UNUSED,
        0,
        939,
        UNUSED,
        610,
        1436,
        UNUSED,
        1065,
        UNUSED,
        0,
        1258,
        -783,
        0,
        526,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        -646,
        0,
        0,
        11,
        -124,
        0,
        UNUSED,
        0,
        UNUSED,
        -37,
        -1627,
        0,
        0,
        604,
        UNUSED,
        0,
        68,
        0,
        0,
        0,
        0,
        UNUSED,
        0,
        -1562,
        0,
        -611,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        -9,
        UNUSED,
        1798,
        905,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -1141,
        UNUSED,
        95,
        UNUSED,
        UNUSED,
        1356,
        -260,
        UNUSED,
        0,
        0,
        0,
        -1768,
        UNUSED,
        -1003,
        0,
        UNUSED,
        1011,
        0,
        0,
        1686,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        58,
        0,
        UNUSED,
        596,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        2491,
        0,
        446,
        UNUSED,
        2109,
        UNUSED,
        UNUSED,
        0,
        0,
        542,
        UNUSED,
        324,
        363,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -879,
        424,
        342,
        -1036,
        0,
        UNUSED,
        UNUSED,
        1898,
        0,
        UNUSED,
        0,
        1224,
        0,
        0,
        UNUSED,
        UNUSED,
        253,
        0,
        UNUSED,
        -1809,
        227,
        1392,
        -1904,
        323,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        743,
        -1884,
        -937,
        -197,
        725,
        581,
        1048,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1144,
        910,
        0,
        1514,
        722,
        UNUSED,
        UNUSED,
        1384,
        UNUSED,
        UNUSED,
        2295,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -628,
        UNUSED,
        UNUSED,
        UNUSED,
        2755,
        UNUSED,
        UNUSED,
        55,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        361,
        0,
        UNUSED,
        -316,
        UNUSED,
        1276,
        UNUSED,
        135,
        UNUSED,
        9,
        1503,
        UNUSED,
        UNUSED,
        951,
        1415,
        UNUSED,
        418,
        UNUSED,
        -249,
        -906,
        UNUSED,
        1190,
        216,
        -279,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        77,
        -148,
        UNUSED,
        UNUSED,
        0,
        -20,
        UNUSED,
        179,
        -588,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -548,
        1726,
        664,
        UNUSED,
        UNUSED,
        0,
        402,
        -174,
        1088,
        UNUSED,
        53,
        -373,
        175,
        1410,
        UNUSED,
        UNUSED,
        -646,
        0,
        0,
        2319,
        UNUSED,
        0,
        1127,
        -196,
        950,
        -196,
        -358,
        UNUSED,
        1120,
        -676,
        UNUSED,
        -17,
        UNUSED,
        UNUSED,
        218,
        UNUSED,
        UNUSED,
        1200,
        710,
        UNUSED,
        807,
        1262,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1420,
        UNUSED,
        UNUSED,
        1618,
        UNUSED,
        1193,
        UNUSED,
        0,
        99,
        661,
        UNUSED,
        0,
        -1193,
        0,
        UNUSED,
        783,
        UNUSED,
        221,
        728,
        UNUSED,
        UNUSED,
        867,
        0,
        520,
        906,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -865,
        UNUSED,
        723,
        UNUSED,
        10,
        0,
        UNUSED,
        1817,
        927,
        669,
        816,
        -358,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        281,
        786,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        857,
        UNUSED,
        -1783,
        UNUSED,
        -801,
        UNUSED,
        0,
        750,
        627,
        484,
        -159,
        UNUSED,
        -283,
        1429,
        UNUSED,
        UNUSED,
        UNUSED,
        1153,
        UNUSED,
        380,
        -375,
        640,
        240,
        1460,
        674,
        2889,
        -1085,
        UNUSED,
        UNUSED,
        317,
        UNUSED,
        410,
        148,
        UNUSED,
        1045,
        UNUSED,
        556,
        UNUSED,
        -530,
        UNUSED,
        0,
        UNUSED,
        1428,
        UNUSED,
        UNUSED,
        680,
        854,
        1952,
        UNUSED,
        UNUSED,
        -752,
        244,
        UNUSED,
        UNUSED,
        1099,
        UNUSED,
        290,
        -558,
        -536,
        -700,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1515,
        UNUSED,
        UNUSED,
        1577,
        -346,
        897,
        UNUSED,
        UNUSED,
        45,
        1076,
        UNUSED,
        -1215,
        0,
        1004,
        UNUSED,
        UNUSED,
        UNUSED,
        -1012,
        565,
        0,
        251,
        44,
        199,
        81,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        371,
        0,
        UNUSED,
        -988,
        -498,
        -1117,
        -15,
        0,
        469,
        1732,
        0,
        704,
        308,
        UNUSED,
        UNUSED,
        -407,
        977,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        272,
        UNUSED,
        619,
        -387,
        833,
        UNUSED,
        276,
        0,
        UNUSED,
        UNUSED,
        426,
        -200,
        UNUSED,
        1010,
        25,
        0,
        1418,
        UNUSED,
        -431,
        244,
        UNUSED,
        UNUSED,
        651,
        UNUSED,
        -1161,
        UNUSED,
        444,
        UNUSED,
        288,
        UNUSED,
        UNUSED,
        UNUSED,
        -457,
        UNUSED,
        563,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        77,
        -8,
        UNUSED,
        1649,
        557,
        0,
        UNUSED,
        0,
        UNUSED,
        489,
        UNUSED,
        UNUSED,
        UNUSED,
        808,
        -1335,
        199,
        1404,
        1118,
        321,
        UNUSED,
        1706,
        UNUSED,
        402,
        UNUSED,
        1210,
        UNUSED,
        UNUSED,
        UNUSED,
        1600,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        1639,
        0,
        UNUSED,
        UNUSED,
        1483,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -263,
        UNUSED,
        -58,
        1453,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1163,
        -211,
        152,
        -328,
        UNUSED,
        858,
        729,
        168,
        UNUSED,
        941,
        276,
        -410,
        UNUSED,
        2427,
        740,
        UNUSED,
        UNUSED,
        UNUSED,
        668,
        UNUSED,
        0,
        0,
        82,
        UNUSED,
        -170,
        UNUSED,
        1054,
        UNUSED,
        UNUSED,
        UNUSED,
        697,
        UNUSED,
        UNUSED,
        -284,
        1190,
        414,
        UNUSED,
        -30,
        0,
        0,
        -731,
        UNUSED,
        UNUSED,
        -471,
        UNUSED,
        834,
        -160,
        474,
        UNUSED,
        UNUSED,
        UNUSED,
        1119,
        233,
        UNUSED,
        869,
        1018,
        UNUSED,
        0,
        1123,
        UNUSED,
        UNUSED,
        UNUSED,
        -2021,
        UNUSED,
        1054,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1127,
        1082,
        0,
        407,
        UNUSED,
        1628,
        1135,
        -260,
        0,
        510,
        UNUSED,
        1140,
        UNUSED,
        232,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        495,
        1246,
        UNUSED,
        0,
        UNUSED,
        -494,
        UNUSED,
        UNUSED,
        UNUSED,
        1117,
        -210,
        UNUSED,
        UNUSED,
        UNUSED,
        -805,
        2398,
        UNUSED,
        0,
        164,
        1435,
        UNUSED,
        UNUSED,
        UNUSED,
        702,
        UNUSED,
        477,
        -400,
        636,
        -1354,
        1670,
        -676,
        1249,
        UNUSED,
        UNUSED,
        19,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1917,
        60,
        UNUSED,
        UNUSED,
        UNUSED,
        367,
        UNUSED,
        UNUSED,
        642,
        UNUSED,
        0,
        86,
        253,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1346,
        1390,
        UNUSED,
        UNUSED,
        747,
        UNUSED,
        UNUSED,
        1519,
        UNUSED,
        UNUSED,
        395,
        977,
        1604,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1536,
        692,
        UNUSED,
        53,
        400,
        827,
        614,
        UNUSED,
        327,
        -930,
        UNUSED,
        UNUSED,
        0,
        -1563,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        1623,
        0,
        0,
        990,
        0,
        UNUSED,
        UNUSED,
        1719,
        256,
        UNUSED,
        -112,
        UNUSED,
        -62,
        398,
        949,
        UNUSED,
        1936,
        UNUSED,
        UNUSED,
        204,
        235,
        UNUSED,
        UNUSED,
        UNUSED,
        -2549,
        811,
        UNUSED,
        1098,
        78,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        212,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        1558,
        UNUSED,
        1725,
        291,
        -545,
        UNUSED,
        120,
        933,
        1430,
        UNUSED,
        -937,
        1230,
        -24,
        -240,
        UNUSED,
        1234,
        UNUSED,
        145,
        UNUSED,
        UNUSED,
        UNUSED,
        761,
        UNUSED,
        364,
        1089,
        343,
        UNUSED,
        -1613,
        -217,
        UNUSED,
        UNUSED,
        1142,
        368,
        1698,
        UNUSED,
        UNUSED,
        UNUSED,
        -803,
        1426,
        1341,
        917,
        UNUSED,
        1007,
        1279,
        -177,
        UNUSED,
        649,
        UNUSED,
        UNUSED,
        UNUSED,
        1583,
        1638,
        UNUSED,
        975,
        UNUSED,
        1334,
        UNUSED,
        842,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1601,
        0,
        1971,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        84,
        UNUSED,
        UNUSED,
        484,
        939,
        UNUSED,
        1566,
        UNUSED,
        753,
        -934,
        -1642,
        417,
        -43,
        887,
        -1918,
        UNUSED,
        -619,
        -53,
        163,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1507,
        432,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -451,
        UNUSED,
        0,
        UNUSED,
        1253,
        1652,
        UNUSED,
        175,
        UNUSED,
        UNUSED,
        397,
        1474,
        1132,
        967,
        487,
        UNUSED,
        1127,
        UNUSED,
        UNUSED,
        1414,
        901,
        UNUSED,
        823,
        35,
        633,
        UNUSED,
        UNUSED,
        UNUSED,
        300,
        1097,
        UNUSED,
        2067,
        -517,
        UNUSED,
        1024,
        456,
        582,
        UNUSED,
        1462,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -550,
        822,
        UNUSED,
        848,
        1964,
        UNUSED,
        0,
        0,
        1107,
        UNUSED,
        1544,
        UNUSED,
        -1883,
        -392,
        UNUSED,
        -508,
        UNUSED,
        UNUSED,
        947,
        745,
        840,
        UNUSED,
        -295,
        1026,
        1655,
        1520,
        UNUSED,
        1671,
        UNUSED,
        1489,
        340,
        UNUSED,
        -582,
        UNUSED,
        58,
        UNUSED,
        UNUSED,
        351,
        836,
        600,
        UNUSED,
        386,
        -2108,
        504,
        0,
        UNUSED,
        UNUSED,
        126,
        1095,
        UNUSED,
        159,
        UNUSED,
        UNUSED,
        1411,
        UNUSED,
        UNUSED,
        1128,
        UNUSED,
        506,
        1105,
        1001,
        UNUSED,
        UNUSED,
        0,
        346,
        1339,
        865,
        0,
        UNUSED,
        UNUSED,
        579,
        475,
        UNUSED,
        UNUSED,
        278,
        UNUSED,
        -184,
        1068,
        1135,
        UNUSED,
        UNUSED,
        1542,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        838,
        1625,
        872,
        1237,
        UNUSED,
        1575,
        21,
        UNUSED,
        626,
        885,
        UNUSED,
        UNUSED,
        -124,
        1245,
        0,
        28,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1833,
        -42,
        UNUSED,
        -446,
        1005,
        UNUSED,
        UNUSED,
        UNUSED,
        843,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        1061,
        118,
        1033,
        570,
        1302,
        2372,
        535,
        UNUSED,
        813,
        UNUSED,
        581,
        2070,
        UNUSED,
        UNUSED,
        548,
        UNUSED,
        UNUSED,
        480,
        1372,
        UNUSED,
        0,
        707,
        UNUSED,
        UNUSED,
        UNUSED,
        384,
        530,
        1486,
        -668,
        2615,
        UNUSED,
        -278,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        617,
        UNUSED,
        56,
        UNUSED,
        -112,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        307,
        -667,
        UNUSED,
        173,
        1389,
        1345,
        235,
        -559,
        -150,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -469,
        749,
        697,
        480,
        UNUSED,
        1106,
        UNUSED,
        UNUSED,
        262,
        645,
        931,
        UNUSED,
        UNUSED,
        -190,
        UNUSED,
        1049,
        1562,
        UNUSED,
        -800,
        UNUSED,
        UNUSED,
        UNUSED,
        -562,
        0,
        -437,
        UNUSED,
        UNUSED,
        1017,
        0,
        928,
        -624,
        -95,
        180,
        1691,
        UNUSED,
        UNUSED,
        538,
        UNUSED,
        -640,
        678,
        UNUSED,
        467,
        121,
        UNUSED,
        -91,
        700,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        2030,
        1331,
        382,
        849,
        780,
        318,
        1410,
        1241,
        UNUSED,
        UNUSED,
        565,
        UNUSED,
        1403,
        208,
        443,
        UNUSED,
        -572,
        378,
        UNUSED,
        UNUSED,
        48,
        UNUSED,
        UNUSED,
        75,
        UNUSED,
        UNUSED,
        240,
        0,
        -211,
        UNUSED,
        UNUSED,
        -176,
        UNUSED,
        UNUSED,
        19,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        893,
        1267,
        -101,
        UNUSED,
        UNUSED,
        UNUSED,
        2033,
        528,
        296,
        987,
        UNUSED,
        UNUSED,
        -32,
        335,
        UNUSED,
        1196,
        1181,
        940,
        UNUSED,
        UNUSED,
        UNUSED,
        1262,
        7,
        1655,
        1177,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -105,
        1602,
        0,
        UNUSED,
        909,
        UNUSED,
        263,
        138,
        UNUSED,
        UNUSED,
        1481,
        1263,
        0,
        UNUSED,
        -437,
        379,
        55,
        1369,
        UNUSED,
        UNUSED,
        211,
        UNUSED,
        UNUSED,
        -141,
        880,
        UNUSED,
        1748,
        1285,
        864,
        UNUSED,
        UNUSED,
        823,
        UNUSED,
        UNUSED,
        898,
        UNUSED,
        1651,
        785,
        UNUSED,
        UNUSED,
        -122,
        1210,
        1683,
        -685,
        391,
        540,
        1066,
        352,
        UNUSED,
        577,
        UNUSED,
        346,
        1148,
        UNUSED,
        862,
        UNUSED,
        -2197,
        1072,
        UNUSED,
        855,
        -297,
        2030,
        UNUSED,
        55,
        -276,
        UNUSED,
        1525,
        383,
        UNUSED,
        UNUSED,
        UNUSED,
        517,
        UNUSED,
        1894,
        UNUSED,
        953,
        UNUSED,
        269,
        UNUSED,
        1207,
        247,
        -698,
        UNUSED,
        UNUSED,
        713,
        868,
        UNUSED,
        260,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        407,
        UNUSED,
        UNUSED,
        -863,
        1067,
        0,
        1136,
        507,
        791,
        UNUSED,
        1669,
        UNUSED,
        482,
        936,
        1291,
        1027,
        -56,
        UNUSED,
        -352,
        UNUSED,
        461,
        1002,
        886,
        UNUSED,
        -410,
        UNUSED,
        -956,
        UNUSED,
        342,
        UNUSED,
        UNUSED,
        UNUSED,
        1882,
        UNUSED,
        1536,
        768,
        1036,
        222,
        UNUSED,
        -1012,
        UNUSED,
        UNUSED,
        840,
        1484,
        UNUSED,
        570,
        UNUSED,
        1051,
        UNUSED,
        299,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        719,
        UNUSED,
        1340,
        -756,
        UNUSED,
        0,
        740,
        798,
        UNUSED,
        723,
        UNUSED,
        1744,
        UNUSED,
        991,
        UNUSED,
        UNUSED,
        UNUSED,
        1176,
        -628,
        UNUSED,
        -1942,
        1511,
        -473,
        -719,
        995,
        UNUSED,
        -353,
        UNUSED,
        -112,
        UNUSED,
        758,
        1515,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        295,
        722,
        1260,
        UNUSED,
        UNUSED,
        1234,
        UNUSED,
        340,
        UNUSED,
        1348,
        1001,
        1305,
        UNUSED,
        -105,
        642,
        UNUSED,
        1665,
        418,
        40,
        346,
        625,
        1843,
        756,
        UNUSED,
        -902,
        UNUSED,
        125,
        1228,
        UNUSED,
        2,
        10,
        UNUSED,
        651,
        -377,
        1959,
        -929,
        51,
        UNUSED,
        UNUSED,
        1460,
        UNUSED,
        UNUSED,
        -600,
        UNUSED,
        847,
        UNUSED,
        904,
        UNUSED,
        1215,
        1585,
        331,
        43,
        1390,
        388,
        108,
        -62,
        1552,
        UNUSED,
        UNUSED,
        141,
        46,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -369,
        275,
        UNUSED,
        1189,
        -50,
        UNUSED,
        888,
        UNUSED,
        32,
        -804,
        929,
        UNUSED,
        338,
        22,
        -70,
        249,
        UNUSED,
        1006,
        UNUSED,
        UNUSED,
        51,
        -160,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        654,
        1212,
        UNUSED,
        UNUSED,
        UNUSED,
        861,
        UNUSED,
        UNUSED,
        -1815,
        773,
        UNUSED,
        UNUSED,
        332,
        -888,
        UNUSED,
        536,
        UNUSED,
        63,
        1337,
        583,
        1593,
        -1178,
        UNUSED,
        UNUSED,
    };
    static const int16_t hash2[2048] = {
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        676,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        311,
        0,
        UNUSED,
        UNUSED,
        3566,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        54,
        UNUSED,
        0,
        0,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        -947,
        651,
        0,
        UNUSED,
        0,
        3512,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        587,
        0,
        UNUSED,
        0,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        357,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        -564,
        0,
        -66,
        1220,
        UNUSED,
        0,
        0,
        1109,
        0,
        UNUSED,
        UNUSED,
        -1306,
        0,
        711,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        78,
        0,
        -583,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        2700,
        UNUSED,
        UNUSED,
        0,
        223,
        1609,
        0,
        696,
        UNUSED,
        945,
        0,
        UNUSED,
        -866,
        UNUSED,
        UNUSED,
        UNUSED,
        -740,
        0,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        -1250,
        2207,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        1469,
        UNUSED,
        UNUSED,
        171,
        UNUSED,
        0,
        1545,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        912,
        UNUSED,
        0,
        791,
        UNUSED,
        UNUSED,
        0,
        313,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        -583,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        764,
        430,
        1254,
        UNUSED,
        0,
        1616,
        UNUSED,
        1115,
        UNUSED,
        1077,
        0,
        0,
        0,
        2169,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        -174,
        1501,
        398,
        UNUSED,
        2485,
        UNUSED,
        310,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        2227,
        UNUSED,
        UNUSED,
        0,
        0,
        0,
        UNUSED,
        0,
        UNUSED,
        2886,
        0,
        0,
        0,
        0,
        UNUSED,
        0,
        0,
        UNUSED,
        0,
        0,
        696,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        2649,
        449,
        3468,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -819,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        0,
        1328,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        1463,
        UNUSED,
        -609,
        1505,
        UNUSED,
        UNUSED,
        143,
        UNUSED,
        0,
        1391,
        456,
        516,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        690,
        0,
        0,
        UNUSED,
        1996,
        UNUSED,
        UNUSED,
        UNUSED,
        -1024,
        UNUSED,
        1044,
        UNUSED,
        0,
        -1208,
        UNUSED,
        -427,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        129,
        UNUSED,
        0,
        UNUSED,
        2511,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        -604,
        0,
        1046,
        -241,
        UNUSED,
        UNUSED,
        1723,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        1026,
        UNUSED,
        UNUSED,
        -761,
        0,
        343,
        383,
        124,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        419,
        1101,
        0,
        0,
        2578,
        UNUSED,
        2532,
        0,
        UNUSED,
        0,
        421,
        1437,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        311,
        UNUSED,
        UNUSED,
        365,
        UNUSED,
        -200,
        0,
        0,
        UNUSED,
        1133,
        -656,
        1001,
        182,
        UNUSED,
        0,
        0,
        3226,
        UNUSED,
        1183,
        UNUSED,
        UNUSED,
        725,
        0,
        UNUSED,
        0,
        0,
        2367,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        655,
        1700,
        0,
        UNUSED,
        428,
        38,
        UNUSED,
        0,
        -572,
        UNUSED,
        UNUSED,
        408,
        UNUSED,
        0,
        1534,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        217,
        2339,
        UNUSED,
        0,
        UNUSED,
        0,
        1728,
        0,
        2254,
        0,
        -718,
        240,
        UNUSED,
        UNUSED,
        UNUSED,
        1424,
        UNUSED,
        UNUSED,
        0,
        1724,
        239,
        UNUSED,
        UNUSED,
        UNUSED,
        429,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        3305,
        UNUSED,
        0,
        0,
        0,
        1637,
        2131,
        0,
        1131,
        UNUSED,
        -234,
        0,
        0,
        UNUSED,
        0,
        -826,
        924,
        UNUSED,
        UNUSED,
        1429,
        800,
        0,
        0,
        UNUSED,
        -180,
        2627,
        2013,
        UNUSED,
        991,
        -177,
        -122,
        0,
        UNUSED,
        105,
        481,
        0,
        1707,
        UNUSED,
        760,
        UNUSED,
        UNUSED,
        UNUSED,
        509,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1015,
        164,
        UNUSED,
        0,
        -87,
        224,
        UNUSED,
        27,
        -313,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        0,
        -170,
        2717,
        -966,
        UNUSED,
        3155,
        0,
        UNUSED,
        0,
        688,
        0,
        0,
        UNUSED,
        -103,
        1378,
        UNUSED,
        UNUSED,
        1020,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        984,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        2159,
        0,
        762,
        UNUSED,
        0,
        907,
        UNUSED,
        UNUSED,
        878,
        UNUSED,
        -1000,
        320,
        -462,
        -572,
        UNUSED,
        0,
        -361,
        75,
        0,
        UNUSED,
        1219,
        880,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        421,
        UNUSED,
        1186,
        -1640,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        1621,
        2067,
        0,
        UNUSED,
        -176,
        -172,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        1885,
        0,
        UNUSED,
        0,
        UNUSED,
        0,
        UNUSED,
        903,
        404,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        187,
        132,
        0,
        UNUSED,
        1606,
        0,
        1321,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -62,
        1374,
        UNUSED,
        851,
        725,
        0,
        UNUSED,
        UNUSED,
        1086,
        UNUSED,
        163,
        UNUSED,
        623,
        969,
        UNUSED,
        UNUSED,
        UNUSED,
        1620,
        559,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        -1003,
        1408,
        UNUSED,
        245,
        0,
        UNUSED,
        UNUSED,
        1506,
        0,
        1288,
        UNUSED,
        UNUSED,
        641,
        UNUSED,
        UNUSED,
        UNUSED,
        403,
        -529,
        -360,
        -1228,
        UNUSED,
        UNUSED,
        0,
        -893,
        1373,
        0,
        659,
        UNUSED,
        999,
        1225,
        UNUSED,
        177,
        1357,
        52,
        UNUSED,
        -263,
        UNUSED,
        0,
        0,
        108,
        UNUSED,
        1560,
        -1044,
        UNUSED,
        -766,
        UNUSED,
        23,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        0,
        797,
        0,
        UNUSED,
        1050,
        UNUSED,
        UNUSED,
        UNUSED,
        1355,
        -215,
        -27,
        UNUSED,
        UNUSED,
        739,
        UNUSED,
        -509,
        UNUSED,
        864,
        UNUSED,
        UNUSED,
        1141,
        941,
        0,
        UNUSED,
        UNUSED,
        0,
        0,
        1257,
        -58,
        1151,
        0,
        37,
        UNUSED,
        UNUSED,
        UNUSED,
        1383,
        0,
        1110,
        225,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        552,
        799,
        189,
        455,
        UNUSED,
        -1351,
        -256,
        84,
        564,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        494,
        UNUSED,
        UNUSED,
        154,
        UNUSED,
        355,
        0,
        UNUSED,
        355,
        0,
        1718,
        1182,
        484,
        UNUSED,
        UNUSED,
        0,
        0,
        UNUSED,
        UNUSED,
        598,
        UNUSED,
        0,
        550,
        UNUSED,
        0,
        UNUSED,
        72,
        UNUSED,
        UNUSED,
        933,
        0,
        1609,
        184,
        1158,
        10,
        UNUSED,
        UNUSED,
        471,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        208,
        460,
        1508,
        1800,
        637,
        237,
        -105,
        0,
        UNUSED,
        UNUSED,
        0,
        385,
        UNUSED,
        0,
        0,
        UNUSED,
        541,
        -921,
        18,
        UNUSED,
        UNUSED,
        0,
        148,
        0,
        293,
        273,
        UNUSED,
        UNUSED,
        672,
        351,
        UNUSED,
        0,
        -311,
        UNUSED,
        262,
        0,
        -565,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        994,
        824,
        UNUSED,
        476,
        UNUSED,
        UNUSED,
        523,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        505,
        1391,
        UNUSED,
        UNUSED,
        0,
        730,
        UNUSED,
        78,
        UNUSED,
        997,
        0,
        0,
        605,
        459,
        UNUSED,
        1534,
        -15,
        0,
        804,
        UNUSED,
        UNUSED,
        488,
        140,
        484,
        UNUSED,
        0,
        UNUSED,
        -344,
        0,
        UNUSED,
        -611,
        UNUSED,
        464,
        UNUSED,
        UNUSED,
        -607,
        220,
        824,
        UNUSED,
        0,
        0,
        0,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1617,
        UNUSED,
        UNUSED,
        134,
        UNUSED,
        -308,
        515,
        0,
        -596,
        UNUSED,
        485,
        1197,
        UNUSED,
        390,
        760,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        58,
        UNUSED,
        1063,
        1198,
        1517,
        132,
        52,
        2005,
        790,
        UNUSED,
        UNUSED,
        1487,
        UNUSED,
        0,
        533,
        UNUSED,
        UNUSED,
        700,
        UNUSED,
        UNUSED,
        0,
        753,
        1253,
        UNUSED,
        1649,
        UNUSED,
        UNUSED,
        605,
        0,
        635,
        UNUSED,
        341,
        0,
        128,
        0,
        278,
        UNUSED,
        1753,
        0,
        1047,
        1991,
        UNUSED,
        UNUSED,
        424,
        UNUSED,
        UNUSED,
        UNUSED,
        1370,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        39,
        UNUSED,
        1239,
        301,
        0,
        1223,
        1532,
        -729,
        UNUSED,
        UNUSED,
        UNUSED,
        -767,
        520,
        -124,
        -129,
        UNUSED,
        0,
        0,
        UNUSED,
        -588,
        358,
        -1198,
        UNUSED,
        UNUSED,
        UNUSED,
        703,
        1509,
        UNUSED,
        UNUSED,
        -525,
        1671,
        UNUSED,
        1599,
        UNUSED,
        0,
        UNUSED,
        477,
        1659,
        0,
        UNUSED,
        680,
        UNUSED,
        94,
        UNUSED,
        1704,
        UNUSED,
        UNUSED,
        UNUSED,
        -623,
        UNUSED,
        1327,
        UNUSED,
        UNUSED,
        UNUSED,
        1425,
        UNUSED,
        777,
        1569,
        UNUSED,
        630,
        UNUSED,
        -139,
        1122,
        0,
        UNUSED,
        774,
        -102,
        231,
        1495,
        486,
        -300,
        217,
        1028,
        1175,
        825,
        565,
        1115,
        -1380,
        UNUSED,
        703,
        1193,
        1677,
        UNUSED,
        1474,
        442,
        UNUSED,
        329,
        2551,
        1107,
        1246,
        1695,
        UNUSED,
        737,
        UNUSED,
        1713,
        0,
        UNUSED,
        UNUSED,
        226,
        UNUSED,
        -330,
        1080,
        UNUSED,
        1523,
        0,
        UNUSED,
        1471,
        -188,
        1541,
        894,
        1104,
        UNUSED,
        1661,
        UNUSED,
        UNUSED,
        706,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        2944,
        593,
        742,
        0,
        UNUSED,
        UNUSED,
        -844,
        18,
        UNUSED,
        892,
        UNUSED,
        UNUSED,
        995,
        -934,
        -307,
        UNUSED,
        -232,
        -383,
        835,
        UNUSED,
        UNUSED,
        UNUSED,
        1493,
        UNUSED,
        576,
        UNUSED,
        1533,
        UNUSED,
        UNUSED,
        1309,
        1199,
        -523,
        UNUSED,
        UNUSED,
        491,
        UNUSED,
        669,
        1708,
        UNUSED,
        1307,
        -962,
        UNUSED,
        UNUSED,
        UNUSED,
        -1236,
        1013,
        410,
        179,
        0,
        -98,
        UNUSED,
        181,
        0,
        1559,
        UNUSED,
        -394,
        2480,
        UNUSED,
        232,
        1111,
        107,
        853,
        1557,
        0,
        UNUSED,
        UNUSED,
        753,
        UNUSED,
        UNUSED,
        UNUSED,
        49,
        0,
        1395,
        UNUSED,
        1385,
        UNUSED,
        -362,
        -1345,
        UNUSED,
        983,
        UNUSED,
        1711,
        -574,
        797,
        1199,
        UNUSED,
        537,
        0,
        -234,
        UNUSED,
        UNUSED,
        1231,
        UNUSED,
        317,
        1492,
        566,
        -1161,
        929,
        -726,
        1593,
        UNUSED,
        UNUSED,
        -438,
        -12,
        UNUSED,
        718,
        965,
        1412,
        -1544,
        1089,
        0,
        UNUSED,
        UNUSED,
        1103,
        687,
        UNUSED,
        UNUSED,
        89,
        1646,
        UNUSED,
        1033,
        UNUSED,
        405,
        UNUSED,
        UNUSED,
        1052,
        57,
        1766,
        667,
        1543,
        1713,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        59,
        15,
        UNUSED,
        559,
        179,
        1452,
        -78,
        1159,
        729,
        0,
        UNUSED,
        348,
        1590,
        390,
        UNUSED,
        UNUSED,
        396,
        UNUSED,
        1516,
        365,
        UNUSED,
        1676,
        UNUSED,
        206,
        1587,
        0,
        0,
        UNUSED,
        24,
        UNUSED,
        219,
        1236,
        UNUSED,
        412,
        1204,
        UNUSED,
        902,
        916,
        280,
        -1474,
        UNUSED,
        UNUSED,
        163,
        UNUSED,
        UNUSED,
        0,
        1584,
        UNUSED,
        1591,
        1396,
        1342,
        448,
        590,
        UNUSED,
        1083,
        UNUSED,
        UNUSED,
        1491,
        401,
        UNUSED,
        912,
        UNUSED,
        230,
        UNUSED,
        -609,
        -506,
        1059,
        UNUSED,
        942,
        1490,
        79,
        521,
        1073,
        393,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        0,
        1221,
        UNUSED,
        UNUSED,
        -906,
        1930,
        1693,
        UNUSED,
        1530,
        700,
        1672,
        344,
        UNUSED,
        UNUSED,
        UNUSED,
        1356,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        25,
        0,
        UNUSED,
        771,
        UNUSED,
        371,
        UNUSED,
        252,
        436,
        UNUSED,
        -511,
        UNUSED,
        875,
        -740,
        UNUSED,
        0,
        1596,
        1077,
        1203,
        1572,
        UNUSED,
        1656,
        374,
        27,
        1684,
        493,
        192,
        1144,
        1246,
        0,
        1518,
        1702,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        1233,
        UNUSED,
        155,
        UNUSED,
        1104,
        UNUSED,
        UNUSED,
        462,
        1300,
        UNUSED,
        -182,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        1255,
        UNUSED,
        UNUSED,
        229,
        268,
        UNUSED,
        UNUSED,
        1092,
        2267,
        -23,
        1117,
        0,
        UNUSED,
        UNUSED,
        -464,
        384,
        1475,
        UNUSED,
        UNUSED,
        -1237,
        UNUSED,
        1128,
        UNUSED,
        UNUSED,
        938,
        -1474,
        932,
        1325,
        876,
        820,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1065,
        UNUSED,
        UNUSED,
        UNUSED,
        1303,
        UNUSED,
        UNUSED,
        445,
        UNUSED,
        1223,
        UNUSED,
        UNUSED,
        UNUSED,
        -38,
        -870,
        UNUSED,
        -129,
        1519,
        UNUSED,
        0,
        -30,
        UNUSED,
        69,
        -858,
        940,
        163,
        UNUSED,
        980,
        60,
        UNUSED,
        548,
        -707,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        432,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1235,
        UNUSED,
        109,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        161,
        421,
        UNUSED,
        1595,
        UNUSED,
        465,
        UNUSED,
        UNUSED,
        23,
        1557,
        1491,
        89,
        -427,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        2101,
        UNUSED,
        UNUSED,
        0,
        UNUSED,
        UNUSED,
        -129,
        -1793,
        -527,
        1129,
        -606,
        176,
        865,
        UNUSED,
        483,
        -173,
        629,
        UNUSED,
        965,
        439,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        1525,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        667,
        293,
        0,
        555,
        0,
        1588,
        2433,
        UNUSED,
        UNUSED,
        298,
        0,
        2436,
        UNUSED,
        UNUSED,
        -1099,
        UNUSED,
        UNUSED,
        304,
        UNUSED,
        856,
        962,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        205,
        UNUSED,
        726,
        -1166,
        1218,
        UNUSED,
        57,
        454,
        -40,
        UNUSED,
        UNUSED,
        -666,
        UNUSED,
        1316,
        382,
        UNUSED,
        UNUSED,
        416,
        UNUSED,
        UNUSED,
        1478,
        859,
        573,
        -1049,
        UNUSED,
        988,
        946,
        67,
        732,
        726,
        -191,
        260,
        1512,
        1266,
        79,
        239,
        UNUSED,
        UNUSED,
        729,
        1088,
        1024,
        -600,
        -819,
        481,
        UNUSED,
        UNUSED,
        1192,
        0,
        UNUSED,
        UNUSED,
        0,
        -658,
        UNUSED,
        116,
        UNUSED,
        UNUSED,
        UNUSED,
        13,
        122,
        1177,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        137,
        0,
        UNUSED,
        UNUSED,
        UNUSED,
        251,
        UNUSED,
        UNUSED,
        UNUSED,
        94,
        1455,
        UNUSED,
        UNUSED,
        UNUSED,
        1891,
        UNUSED,
        1312,
        UNUSED,
        1367,
        716,
        1633,
        346,
        1431,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        406,
        783,
        146,
        -1098,
        147,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        2206,
        303,
        963,
        1026,
        33,
        UNUSED,
        1506,
        UNUSED,
        UNUSED,
        2361,
        UNUSED,
        -821,
        -748,
        -750,
        1133,
        UNUSED,
        UNUSED,
        802,
        25,
        UNUSED,
        682,
        UNUSED,
        1081,
        380,
        UNUSED,
        UNUSED,
        833,
        UNUSED,
        461,
        288,
        UNUSED,
        UNUSED,
        UNUSED,
        213,
        825,
        1604,
        1445,
        585,
        UNUSED,
        -380,
        1642,
        UNUSED,
        UNUSED,
        1690,
        UNUSED,
        1304,
        UNUSED,
        UNUSED,
        81,
        UNUSED,
        UNUSED,
        UNUSED,
        479,
        UNUSED,
        -364,
        634,
        UNUSED,
        1827,
        UNUSED,
        3175,
        786,
        -302,
        UNUSED,
        UNUSED,
        839,
        1079,
        806,
        139,
        1350,
        UNUSED,
        797,
        UNUSED,
        183,
        396,
        UNUSED,
        UNUSED,
        UNUSED,
        322,
        356,
        705,
        195,
        1625,
        UNUSED,
        UNUSED,
        284,
        UNUSED,
        UNUSED,
        UNUSED,
        717,
        741,
        0,
        1537,
        575,
        400,
        925,
        1042,
        1419,
        UNUSED,
        -260,
        683,
        1137,
        1229,
        919,
        1021,
        UNUSED,
        1712,
        0,
        1272,
        UNUSED,
        -896,
        0,
        695,
        1338,
        UNUSED,
        UNUSED,
        286,
        UNUSED,
        UNUSED,
        UNUSED,
        1479,
        UNUSED,
        158,
        UNUSED,
        1979,
        119,
        UNUSED,
        1093,
        UNUSED,
        -25,
        3335,
        576,
        UNUSED,
        -249,
        1549,
        114,
        485,
        -349,
        UNUSED,
        413,
        UNUSED,
        -218,
        -568,
        221,
        228,
        1554,
        -1243,
        UNUSED,
        0,
        1548,
        1727,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        -95,
        UNUSED,
        UNUSED,
        4,
        548,
        UNUSED,
        UNUSED,
        0,
        1634,
        225,
        UNUSED,
        UNUSED,
        525,
        UNUSED,
        596,
        -987,
        130,
        489,
        921,
        UNUSED,
        1585,
        UNUSED,
        UNUSED,
        -735,
        UNUSED,
        1640,
        UNUSED,
        UNUSED,
        -880,
        UNUSED,
        UNUSED,
        UNUSED,
        940,
        -864,
        UNUSED,
        -634,
        UNUSED,
        UNUSED,
        326,
        748,
        UNUSED,
        591,
        UNUSED,
        781,
        532,
        119,
        UNUSED,
        -379,
        UNUSED,
        3560,
        1094,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        42,
        UNUSED,
        976,
        848,
        UNUSED,
        234,
        UNUSED,
        UNUSED,
        UNUSED,
        545,
        UNUSED,
        -685,
        UNUSED,
        287,
        3070,
        UNUSED,
        60,
        1477,
        -923,
        -1232,
        UNUSED,
        UNUSED,
        UNUSED,
        1130,
        681,
        UNUSED,
        -962,
        -40,
        UNUSED,
        UNUSED,
        281,
        1529,
        UNUSED,
        -1057,
        -582,
        1429,
        UNUSED,
        UNUSED,
        959,
        UNUSED,
        -1874,
        -267,
        UNUSED,
        1070,
        UNUSED,
        -1360,
        UNUSED,
        1298,
        622,
        UNUSED,
        UNUSED,
        534,
        1455,
        549,
        UNUSED,
        UNUSED,
        1308,
        UNUSED,
        -749,
        295,
        201,
        UNUSED,
        UNUSED,
        624,
        UNUSED,
        979,
        689,
        1141,
        UNUSED,
        914,
        UNUSED,
        1113,
        UNUSED,
        910,
        148,
        302,
        1058,
        219,
        437,
        UNUSED,
        UNUSED,
        860,
        -574,
        5,
        1248,
        UNUSED,
        UNUSED,
        1614,
        UNUSED,
        2660,
        UNUSED,
        1386,
        -171,
        665,
        758,
        UNUSED,
        305,
        1161,
        UNUSED,
        666,
        798,
        UNUSED,
        89,
        498,
        UNUSED,
        1250,
        1611,
        UNUSED,
        UNUSED,
        -168,
        UNUSED,
        -1259,
        UNUSED,
        1264,
        935,
        UNUSED,
        UNUSED,
        672,
        -1534,
        UNUSED,
        63,
        UNUSED,
        UNUSED,
        72,
        UNUSED,
        1210,
        UNUSED,
        UNUSED,
        602,
        UNUSED,
        76,
        1032,
        231,
        UNUSED,
        1352,
        235,
        UNUSED,
        1635,
        74,
        319,
        UNUSED,
        -748,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        UNUSED,
        489,
        1641,
        -1048,
        UNUSED,
        1310,
        UNUSED,
        UNUSED,
        130,
        135,
        UNUSED,
        UNUSED,
        491,
    };
    static const struct tokendata tokendata[1732] = {
        { "db", TOKEN_INSN, C_none, I_DB },
        { "dw", TOKEN_INSN, C_none, I_DW },
        { "dd", TOKEN_INSN, C_none, I_DD },
        { "dq", TOKEN_INSN, C_none, I_DQ },
        { "dt", TOKEN_INSN, C_none, I_DT },
        { "do", TOKEN_INSN, C_none, I_DO },
        { "dy", TOKEN_INSN, C_none, I_DY },
        { "resb", TOKEN_INSN, C_none, I_RESB },
        { "resw", TOKEN_INSN, C_none, I_RESW },
        { "resd", TOKEN_INSN, C_none, I_RESD },
        { "resq", TOKEN_INSN, C_none, I_RESQ },
        { "rest", TOKEN_INSN, C_none, I_REST },
        { "reso", TOKEN_INSN, C_none, I_RESO },
        { "resy", TOKEN_INSN, C_none, I_RESY },
        { "aaa", TOKEN_INSN, C_none, I_AAA },
        { "aad", TOKEN_INSN, C_none, I_AAD },
        { "aam", TOKEN_INSN, C_none, I_AAM },
        { "aas", TOKEN_INSN, C_none, I_AAS },
        { "adc", TOKEN_INSN, C_none, I_ADC },
        { "add", TOKEN_INSN, C_none, I_ADD },
        { "and", TOKEN_INSN, C_none, I_AND },
        { "arpl", TOKEN_INSN, C_none, I_ARPL },
        { "bb0_reset", TOKEN_INSN, C_none, I_BB0_RESET },
        { "bb1_reset", TOKEN_INSN, C_none, I_BB1_RESET },
        { "bound", TOKEN_INSN, C_none, I_BOUND },
        { "bsf", TOKEN_INSN, C_none, I_BSF },
        { "bsr", TOKEN_INSN, C_none, I_BSR },
        { "bswap", TOKEN_INSN, C_none, I_BSWAP },
        { "bt", TOKEN_INSN, C_none, I_BT },
        { "btc", TOKEN_INSN, C_none, I_BTC },
        { "btr", TOKEN_INSN, C_none, I_BTR },
        { "bts", TOKEN_INSN, C_none, I_BTS },
        { "call", TOKEN_INSN, C_none, I_CALL },
        { "cbw", TOKEN_INSN, C_none, I_CBW },
        { "cdq", TOKEN_INSN, C_none, I_CDQ },
        { "clc", TOKEN_INSN, C_none, I_CLC },
        { "cld", TOKEN_INSN, C_none, I_CLD },
        { "cli", TOKEN_INSN, C_none, I_CLI },
        { "clts", TOKEN_INSN, C_none, I_CLTS },
        { "cmc", TOKEN_INSN, C_none, I_CMC },
        { "cmp", TOKEN_INSN, C_none, I_CMP },
        { "cmpsb", TOKEN_INSN, C_none, I_CMPSB },
        { "cmpsd", TOKEN_INSN, C_none, I_CMPSD },
        { "cmpsw", TOKEN_INSN, C_none, I_CMPSW },
        { "cmpxchg", TOKEN_INSN, C_none, I_CMPXCHG },
        { "cmpxchg486", TOKEN_INSN, C_none, I_CMPXCHG486 },
        { "cmpxchg8b", TOKEN_INSN, C_none, I_CMPXCHG8B },
        { "cpuid", TOKEN_INSN, C_none, I_CPUID },
        { "cpu_read", TOKEN_INSN, C_none, I_CPU_READ },
        { "cpu_write", TOKEN_INSN, C_none, I_CPU_WRITE },
        { "cwd", TOKEN_INSN, C_none, I_CWD },
        { "cwde", TOKEN_INSN, C_none, I_CWDE },
        { "daa", TOKEN_INSN, C_none, I_DAA },
        { "das", TOKEN_INSN, C_none, I_DAS },
        { "dec", TOKEN_INSN, C_none, I_DEC },
        { "div", TOKEN_INSN, C_none, I_DIV },
        { "dmint", TOKEN_INSN, C_none, I_DMINT },
        { "emms", TOKEN_INSN, C_none, I_EMMS },
        { "enter", TOKEN_INSN, C_none, I_ENTER },
        { "equ", TOKEN_INSN, C_none, I_EQU },
        { "f2xm1", TOKEN_INSN, C_none, I_F2XM1 },
        { "fabs", TOKEN_INSN, C_none, I_FABS },
        { "fadd", TOKEN_INSN, C_none, I_FADD },
        { "faddp", TOKEN_INSN, C_none, I_FADDP },
        { "fbld", TOKEN_INSN, C_none, I_FBLD },
        { "fbstp", TOKEN_INSN, C_none, I_FBSTP },
        { "fchs", TOKEN_INSN, C_none, I_FCHS },
        { "fclex", TOKEN_INSN, C_none, I_FCLEX },
        { "fcmovb", TOKEN_INSN, C_none, I_FCMOVB },
        { "fcmovbe", TOKEN_INSN, C_none, I_FCMOVBE },
        { "fcmove", TOKEN_INSN, C_none, I_FCMOVE },
        { "fcmovnb", TOKEN_INSN, C_none, I_FCMOVNB },
        { "fcmovnbe", TOKEN_INSN, C_none, I_FCMOVNBE },
        { "fcmovne", TOKEN_INSN, C_none, I_FCMOVNE },
        { "fcmovnu", TOKEN_INSN, C_none, I_FCMOVNU },
        { "fcmovu", TOKEN_INSN, C_none, I_FCMOVU },
        { "fcom", TOKEN_INSN, C_none, I_FCOM },
        { "fcomi", TOKEN_INSN, C_none, I_FCOMI },
        { "fcomip", TOKEN_INSN, C_none, I_FCOMIP },
        { "fcomp", TOKEN_INSN, C_none, I_FCOMP },
        { "fcompp", TOKEN_INSN, C_none, I_FCOMPP },
        { "fcos", TOKEN_INSN, C_none, I_FCOS },
        { "fdecstp", TOKEN_INSN, C_none, I_FDECSTP },
        { "fdisi", TOKEN_INSN, C_none, I_FDISI },
        { "fdiv", TOKEN_INSN, C_none, I_FDIV },
        { "fdivp", TOKEN_INSN, C_none, I_FDIVP },
        { "fdivr", TOKEN_INSN, C_none, I_FDIVR },
        { "fdivrp", TOKEN_INSN, C_none, I_FDIVRP },
        { "femms", TOKEN_INSN, C_none, I_FEMMS },
        { "feni", TOKEN_INSN, C_none, I_FENI },
        { "ffree", TOKEN_INSN, C_none, I_FFREE },
        { "ffreep", TOKEN_INSN, C_none, I_FFREEP },
        { "fiadd", TOKEN_INSN, C_none, I_FIADD },
        { "ficom", TOKEN_INSN, C_none, I_FICOM },
        { "ficomp", TOKEN_INSN, C_none, I_FICOMP },
        { "fidiv", TOKEN_INSN, C_none, I_FIDIV },
        { "fidivr", TOKEN_INSN, C_none, I_FIDIVR },
        { "fild", TOKEN_INSN, C_none, I_FILD },
        { "fimul", TOKEN_INSN, C_none, I_FIMUL },
        { "fincstp", TOKEN_INSN, C_none, I_FINCSTP },
        { "finit", TOKEN_INSN, C_none, I_FINIT },
        { "fist", TOKEN_INSN, C_none, I_FIST },
        { "fistp", TOKEN_INSN, C_none, I_FISTP },
        { "fisub", TOKEN_INSN, C_none, I_FISUB },
        { "fisubr", TOKEN_INSN, C_none, I_FISUBR },
        { "fld", TOKEN_INSN, C_none, I_FLD },
        { "fld1", TOKEN_INSN, C_none, I_FLD1 },
        { "fldcw", TOKEN_INSN, C_none, I_FLDCW },
        { "fldenv", TOKEN_INSN, C_none, I_FLDENV },
        { "fldl2e", TOKEN_INSN, C_none, I_FLDL2E },
        { "fldl2t", TOKEN_INSN, C_none, I_FLDL2T },
        { "fldlg2", TOKEN_INSN, C_none, I_FLDLG2 },
        { "fldln2", TOKEN_INSN, C_none, I_FLDLN2 },
        { "fldpi", TOKEN_INSN, C_none, I_FLDPI },
        { "fldz", TOKEN_INSN, C_none, I_FLDZ },
        { "fmul", TOKEN_INSN, C_none, I_FMUL },
        { "fmulp", TOKEN_INSN, C_none, I_FMULP },
        { "fnclex", TOKEN_INSN, C_none, I_FNCLEX },
        { "fndisi", TOKEN_INSN, C_none, I_FNDISI },
        { "fneni", TOKEN_INSN, C_none, I_FNENI },
        { "fninit", TOKEN_INSN, C_none, I_FNINIT },
        { "fnop", TOKEN_INSN, C_none, I_FNOP },
        { "fnsave", TOKEN_INSN, C_none, I_FNSAVE },
        { "fnstcw", TOKEN_INSN, C_none, I_FNSTCW },
        { "fnstenv", TOKEN_INSN, C_none, I_FNSTENV },
        { "fnstsw", TOKEN_INSN, C_none, I_FNSTSW },
        { "fpatan", TOKEN_INSN, C_none, I_FPATAN },
        { "fprem", TOKEN_INSN, C_none, I_FPREM },
        { "fprem1", TOKEN_INSN, C_none, I_FPREM1 },
        { "fptan", TOKEN_INSN, C_none, I_FPTAN },
        { "frndint", TOKEN_INSN, C_none, I_FRNDINT },
        { "frstor", TOKEN_INSN, C_none, I_FRSTOR },
        { "fsave", TOKEN_INSN, C_none, I_FSAVE },
        { "fscale", TOKEN_INSN, C_none, I_FSCALE },
        { "fsetpm", TOKEN_INSN, C_none, I_FSETPM },
        { "fsin", TOKEN_INSN, C_none, I_FSIN },
        { "fsincos", TOKEN_INSN, C_none, I_FSINCOS },
        { "fsqrt", TOKEN_INSN, C_none, I_FSQRT },
        { "fst", TOKEN_INSN, C_none, I_FST },
        { "fstcw", TOKEN_INSN, C_none, I_FSTCW },
        { "fstenv", TOKEN_INSN, C_none, I_FSTENV },
        { "fstp", TOKEN_INSN, C_none, I_FSTP },
        { "fstsw", TOKEN_INSN, C_none, I_FSTSW },
        { "fsub", TOKEN_INSN, C_none, I_FSUB },
        { "fsubp", TOKEN_INSN, C_none, I_FSUBP },
        { "fsubr", TOKEN_INSN, C_none, I_FSUBR },
        { "fsubrp", TOKEN_INSN, C_none, I_FSUBRP },
        { "ftst", TOKEN_INSN, C_none, I_FTST },
        { "fucom", TOKEN_INSN, C_none, I_FUCOM },
        { "fucomi", TOKEN_INSN, C_none, I_FUCOMI },
        { "fucomip", TOKEN_INSN, C_none, I_FUCOMIP },
        { "fucomp", TOKEN_INSN, C_none, I_FUCOMP },
        { "fucompp", TOKEN_INSN, C_none, I_FUCOMPP },
        { "fxam", TOKEN_INSN, C_none, I_FXAM },
        { "fxch", TOKEN_INSN, C_none, I_FXCH },
        { "fxtract", TOKEN_INSN, C_none, I_FXTRACT },
        { "fyl2x", TOKEN_INSN, C_none, I_FYL2X },
        { "fyl2xp1", TOKEN_INSN, C_none, I_FYL2XP1 },
        { "hlt", TOKEN_INSN, C_none, I_HLT },
        { "ibts", TOKEN_INSN, C_none, I_IBTS },
        { "icebp", TOKEN_INSN, C_none, I_ICEBP },
        { "idiv", TOKEN_INSN, C_none, I_IDIV },
        { "imul", TOKEN_INSN, C_none, I_IMUL },
        { "in", TOKEN_INSN, C_none, I_IN },
        { "inc", TOKEN_INSN, C_none, I_INC },
        { "incbin", TOKEN_INSN, C_none, I_INCBIN },
        { "insb", TOKEN_INSN, C_none, I_INSB },
        { "insd", TOKEN_INSN, C_none, I_INSD },
        { "insw", TOKEN_INSN, C_none, I_INSW },
        { "int", TOKEN_INSN, C_none, I_INT },
        { "int01", TOKEN_INSN, C_none, I_INT01 },
        { "int1", TOKEN_INSN, C_none, I_INT1 },
        { "int03", TOKEN_INSN, C_none, I_INT03 },
        { "int3", TOKEN_INSN, C_none, I_INT3 },
        { "into", TOKEN_INSN, C_none, I_INTO },
        { "invd", TOKEN_INSN, C_none, I_INVD },
        { "invlpg", TOKEN_INSN, C_none, I_INVLPG },
        { "iret", TOKEN_INSN, C_none, I_IRET },
        { "iretd", TOKEN_INSN, C_none, I_IRETD },
        { "iretw", TOKEN_INSN, C_none, I_IRETW },
        { "jcxz", TOKEN_INSN, C_none, I_JCXZ },
        { "jecxz", TOKEN_INSN, C_none, I_JECXZ },
        { "jmp", TOKEN_INSN, C_none, I_JMP },
        { "lahf", TOKEN_INSN, C_none, I_LAHF },
        { "lar", TOKEN_INSN, C_none, I_LAR },
        { "lds", TOKEN_INSN, C_none, I_LDS },
        { "lea", TOKEN_INSN, C_none, I_LEA },
        { "leave", TOKEN_INSN, C_none, I_LEAVE },
        { "les", TOKEN_INSN, C_none, I_LES },

        { "lfs", TOKEN_INSN, C_none, I_LFS },
        { "lgdt", TOKEN_INSN, C_none, I_LGDT },
        { "lgs", TOKEN_INSN, C_none, I_LGS },
        { "lidt", TOKEN_INSN, C_none, I_LIDT },
        { "lldt", TOKEN_INSN, C_none, I_LLDT },
        { "lmsw", TOKEN_INSN, C_none, I_LMSW },
        { "loadall", TOKEN_INSN, C_none, I_LOADALL },
        { "loadall286", TOKEN_INSN, C_none, I_LOADALL286 },
        { "lodsb", TOKEN_INSN, C_none, I_LODSB },
        { "lodsd", TOKEN_INSN, C_none, I_LODSD },

        { "lodsw", TOKEN_INSN, C_none, I_LODSW },
        { "loop", TOKEN_INSN, C_none, I_LOOP },
        { "loope", TOKEN_INSN, C_none, I_LOOPE },
        { "loopne", TOKEN_INSN, C_none, I_LOOPNE },
        { "loopnz", TOKEN_INSN, C_none, I_LOOPNZ },
        { "loopz", TOKEN_INSN, C_none, I_LOOPZ },
        { "lsl", TOKEN_INSN, C_none, I_LSL },
        { "lss", TOKEN_INSN, C_none, I_LSS },
        { "ltr", TOKEN_INSN, C_none, I_LTR },


        { "mov", TOKEN_INSN, C_none, I_MOV },
        { "movd", TOKEN_INSN, C_none, I_MOVD },
        { "movq", TOKEN_INSN, C_none, I_MOVQ },
        { "movsb", TOKEN_INSN, C_none, I_MOVSB },
        { "movsd", TOKEN_INSN, C_none, I_MOVSD },

        { "movsw", TOKEN_INSN, C_none, I_MOVSW },
        { "movsx", TOKEN_INSN, C_none, I_MOVSX },

        { "movzx", TOKEN_INSN, C_none, I_MOVZX },
        { "mul", TOKEN_INSN, C_none, I_MUL },

        { "neg", TOKEN_INSN, C_none, I_NEG },
        { "nop", TOKEN_INSN, C_none, I_NOP },
        { "not", TOKEN_INSN, C_none, I_NOT },
        { "or", TOKEN_INSN, C_none, I_OR },
        { "out", TOKEN_INSN, C_none, I_OUT },
        { "outsb", TOKEN_INSN, C_none, I_OUTSB },
        { "outsd", TOKEN_INSN, C_none, I_OUTSD },
        { "outsw", TOKEN_INSN, C_none, I_OUTSW },
        { "packssdw", TOKEN_INSN, C_none, I_PACKSSDW },
        { "packsswb", TOKEN_INSN, C_none, I_PACKSSWB },
        { "packuswb", TOKEN_INSN, C_none, I_PACKUSWB },
        { "paddb", TOKEN_INSN, C_none, I_PADDB },
        { "paddd", TOKEN_INSN, C_none, I_PADDD },
        { "paddsb", TOKEN_INSN, C_none, I_PADDSB },
        { "paddsiw", TOKEN_INSN, C_none, I_PADDSIW },
        { "paddsw", TOKEN_INSN, C_none, I_PADDSW },
        { "paddusb", TOKEN_INSN, C_none, I_PADDUSB },
        { "paddusw", TOKEN_INSN, C_none, I_PADDUSW },
        { "paddw", TOKEN_INSN, C_none, I_PADDW },
        { "pand", TOKEN_INSN, C_none, I_PAND },
        { "pandn", TOKEN_INSN, C_none, I_PANDN },
        { "pause", TOKEN_INSN, C_none, I_PAUSE },
        { "paveb", TOKEN_INSN, C_none, I_PAVEB },
        { "pavgusb", TOKEN_INSN, C_none, I_PAVGUSB },
        { "pcmpeqb", TOKEN_INSN, C_none, I_PCMPEQB },
        { "pcmpeqd", TOKEN_INSN, C_none, I_PCMPEQD },
        { "pcmpeqw", TOKEN_INSN, C_none, I_PCMPEQW },
        { "pcmpgtb", TOKEN_INSN, C_none, I_PCMPGTB },
        { "pcmpgtd", TOKEN_INSN, C_none, I_PCMPGTD },
        { "pcmpgtw", TOKEN_INSN, C_none, I_PCMPGTW },
        { "pdistib", TOKEN_INSN, C_none, I_PDISTIB },
        { "pf2id", TOKEN_INSN, C_none, I_PF2ID },
        { "pfacc", TOKEN_INSN, C_none, I_PFACC },
        { "pfadd", TOKEN_INSN, C_none, I_PFADD },
        { "pfcmpeq", TOKEN_INSN, C_none, I_PFCMPEQ },
        { "pfcmpge", TOKEN_INSN, C_none, I_PFCMPGE },
        { "pfcmpgt", TOKEN_INSN, C_none, I_PFCMPGT },
        { "pfmax", TOKEN_INSN, C_none, I_PFMAX },
        { "pfmin", TOKEN_INSN, C_none, I_PFMIN },
        { "pfmul", TOKEN_INSN, C_none, I_PFMUL },
        { "pfrcp", TOKEN_INSN, C_none, I_PFRCP },
        { "pfrcpit1", TOKEN_INSN, C_none, I_PFRCPIT1 },
        { "pfrcpit2", TOKEN_INSN, C_none, I_PFRCPIT2 },
        { "pfrsqit1", TOKEN_INSN, C_none, I_PFRSQIT1 },
        { "pfrsqrt", TOKEN_INSN, C_none, I_PFRSQRT },
        { "pfsub", TOKEN_INSN, C_none, I_PFSUB },
        { "pfsubr", TOKEN_INSN, C_none, I_PFSUBR },
        { "pi2fd", TOKEN_INSN, C_none, I_PI2FD },
        { "pmachriw", TOKEN_INSN, C_none, I_PMACHRIW },
        { "pmaddwd", TOKEN_INSN, C_none, I_PMADDWD },
        { "pmagw", TOKEN_INSN, C_none, I_PMAGW },
        { "pmulhriw", TOKEN_INSN, C_none, I_PMULHRIW },
        { "pmulhrwa", TOKEN_INSN, C_none, I_PMULHRWA },
        { "pmulhrwc", TOKEN_INSN, C_none, I_PMULHRWC },
        { "pmulhw", TOKEN_INSN, C_none, I_PMULHW },
        { "pmullw", TOKEN_INSN, C_none, I_PMULLW },
        { "pmvgezb", TOKEN_INSN, C_none, I_PMVGEZB },
        { "pmvlzb", TOKEN_INSN, C_none, I_PMVLZB },
        { "pmvnzb", TOKEN_INSN, C_none, I_PMVNZB },
        { "pmvzb", TOKEN_INSN, C_none, I_PMVZB },
        { "pop", TOKEN_INSN, C_none, I_POP },
        { "popa", TOKEN_INSN, C_none, I_POPA },
        { "popad", TOKEN_INSN, C_none, I_POPAD },
        { "popaw", TOKEN_INSN, C_none, I_POPAW },
        { "popf", TOKEN_INSN, C_none, I_POPF },
        { "popfd", TOKEN_INSN, C_none, I_POPFD },

        { "popfw", TOKEN_INSN, C_none, I_POPFW },
        { "por", TOKEN_INSN, C_none, I_POR },
        { "prefetch", TOKEN_INSN, C_none, I_PREFETCH },
        { "prefetchw", TOKEN_INSN, C_none, I_PREFETCHW },
        { "pslld", TOKEN_INSN, C_none, I_PSLLD },
        { "psllq", TOKEN_INSN, C_none, I_PSLLQ },
        { "psllw", TOKEN_INSN, C_none, I_PSLLW },
        { "psrad", TOKEN_INSN, C_none, I_PSRAD },
        { "psraw", TOKEN_INSN, C_none, I_PSRAW },
        { "psrld", TOKEN_INSN, C_none, I_PSRLD },
        { "psrlq", TOKEN_INSN, C_none, I_PSRLQ },
        { "psrlw", TOKEN_INSN, C_none, I_PSRLW },
        { "psubb", TOKEN_INSN, C_none, I_PSUBB },
        { "psubd", TOKEN_INSN, C_none, I_PSUBD },
        { "psubsb", TOKEN_INSN, C_none, I_PSUBSB },
        { "psubsiw", TOKEN_INSN, C_none, I_PSUBSIW },
        { "psubsw", TOKEN_INSN, C_none, I_PSUBSW },
        { "psubusb", TOKEN_INSN, C_none, I_PSUBUSB },
        { "psubusw", TOKEN_INSN, C_none, I_PSUBUSW },
        { "psubw", TOKEN_INSN, C_none, I_PSUBW },
        { "punpckhbw", TOKEN_INSN, C_none, I_PUNPCKHBW },
        { "punpckhdq", TOKEN_INSN, C_none, I_PUNPCKHDQ },
        { "punpckhwd", TOKEN_INSN, C_none, I_PUNPCKHWD },
        { "punpcklbw", TOKEN_INSN, C_none, I_PUNPCKLBW },
        { "punpckldq", TOKEN_INSN, C_none, I_PUNPCKLDQ },
        { "punpcklwd", TOKEN_INSN, C_none, I_PUNPCKLWD },
        { "push", TOKEN_INSN, C_none, I_PUSH },
        { "pusha", TOKEN_INSN, C_none, I_PUSHA },
        { "pushad", TOKEN_INSN, C_none, I_PUSHAD },
        { "pushaw", TOKEN_INSN, C_none, I_PUSHAW },
        { "pushf", TOKEN_INSN, C_none, I_PUSHF },
        { "pushfd", TOKEN_INSN, C_none, I_PUSHFD },

        { "pushfw", TOKEN_INSN, C_none, I_PUSHFW },
        { "pxor", TOKEN_INSN, C_none, I_PXOR },
        { "rcl", TOKEN_INSN, C_none, I_RCL },
        { "rcr", TOKEN_INSN, C_none, I_RCR },
        { "rdshr", TOKEN_INSN, C_none, I_RDSHR },
        { "rdmsr", TOKEN_INSN, C_none, I_RDMSR },
        { "rdpmc", TOKEN_INSN, C_none, I_RDPMC },
        { "rdtsc", TOKEN_INSN, C_none, I_RDTSC },
        { "rdtscp", TOKEN_INSN, C_none, I_RDTSCP },
        { "ret", TOKEN_INSN, C_none, I_RET },
        { "retf", TOKEN_INSN, C_none, I_RETF },
        { "retn", TOKEN_INSN, C_none, I_RETN },
        { "rol", TOKEN_INSN, C_none, I_ROL },
        { "ror", TOKEN_INSN, C_none, I_ROR },
        { "rdm", TOKEN_INSN, C_none, I_RDM },
        { "rsdc", TOKEN_INSN, C_none, I_RSDC },
        { "rsldt", TOKEN_INSN, C_none, I_RSLDT },
        { "rsm", TOKEN_INSN, C_none, I_RSM },
        { "rsts", TOKEN_INSN, C_none, I_RSTS },
        { "sahf", TOKEN_INSN, C_none, I_SAHF },
        { "sal", TOKEN_INSN, C_none, I_SAL },
        { "salc", TOKEN_INSN, C_none, I_SALC },
        { "sar", TOKEN_INSN, C_none, I_SAR },
        { "sbb", TOKEN_INSN, C_none, I_SBB },
        { "scasb", TOKEN_INSN, C_none, I_SCASB },
        { "scasd", TOKEN_INSN, C_none, I_SCASD },

        { "scasw", TOKEN_INSN, C_none, I_SCASW },

        { "sgdt", TOKEN_INSN, C_none, I_SGDT },
        { "shl", TOKEN_INSN, C_none, I_SHL },
        { "shld", TOKEN_INSN, C_none, I_SHLD },
        { "shr", TOKEN_INSN, C_none, I_SHR },
        { "shrd", TOKEN_INSN, C_none, I_SHRD },
        { "sidt", TOKEN_INSN, C_none, I_SIDT },
        { "sldt", TOKEN_INSN, C_none, I_SLDT },

        { "smi", TOKEN_INSN, C_none, I_SMI },
        { "smint", TOKEN_INSN, C_none, I_SMINT },
        { "smintold", TOKEN_INSN, C_none, I_SMINTOLD },
        { "smsw", TOKEN_INSN, C_none, I_SMSW },
        { "stc", TOKEN_INSN, C_none, I_STC },
        { "std", TOKEN_INSN, C_none, I_STD },

        { "sti", TOKEN_INSN, C_none, I_STI },
        { "stosb", TOKEN_INSN, C_none, I_STOSB },
        { "stosd", TOKEN_INSN, C_none, I_STOSD },

        { "stosw", TOKEN_INSN, C_none, I_STOSW },
        { "str", TOKEN_INSN, C_none, I_STR },
        { "sub", TOKEN_INSN, C_none, I_SUB },
        { "svdc", TOKEN_INSN, C_none, I_SVDC },
        { "svldt", TOKEN_INSN, C_none, I_SVLDT },
        { "svts", TOKEN_INSN, C_none, I_SVTS },
        { "syscall", TOKEN_INSN, C_none, I_SYSCALL },
        { "sysenter", TOKEN_INSN, C_none, I_SYSENTER },
        { "sysexit", TOKEN_INSN, C_none, I_SYSEXIT },
        { "sysret", TOKEN_INSN, C_none, I_SYSRET },
        { "test", TOKEN_INSN, C_none, I_TEST },
        { "ud0", TOKEN_INSN, C_none, I_UD0 },
        { "ud1", TOKEN_INSN, C_none, I_UD1 },
        { "ud2b", TOKEN_INSN, C_none, I_UD2B },
        { "ud2", TOKEN_INSN, C_none, I_UD2 },
        { "ud2a", TOKEN_INSN, C_none, I_UD2A },
        { "umov", TOKEN_INSN, C_none, I_UMOV },
        { "verr", TOKEN_INSN, C_none, I_VERR },
        { "verw", TOKEN_INSN, C_none, I_VERW },
        { "fwait", TOKEN_INSN, C_none, I_FWAIT },
        { "wbinvd", TOKEN_INSN, C_none, I_WBINVD },
        { "wrshr", TOKEN_INSN, C_none, I_WRSHR },
        { "wrmsr", TOKEN_INSN, C_none, I_WRMSR },
        { "xadd", TOKEN_INSN, C_none, I_XADD },
        { "xbts", TOKEN_INSN, C_none, I_XBTS },
        { "xchg", TOKEN_INSN, C_none, I_XCHG },
        { "xlatb", TOKEN_INSN, C_none, I_XLATB },
        { "xlat", TOKEN_INSN, C_none, I_XLAT },
        { "xor", TOKEN_INSN, C_none, I_XOR },
        { "cmova", TOKEN_INSN, C_A, I_CMOVcc },
        { "cmovae", TOKEN_INSN, C_AE, I_CMOVcc },
        { "cmovb", TOKEN_INSN, C_B, I_CMOVcc },
        { "cmovbe", TOKEN_INSN, C_BE, I_CMOVcc },
        { "cmovc", TOKEN_INSN, C_C, I_CMOVcc },
        { "cmove", TOKEN_INSN, C_E, I_CMOVcc },
        { "cmovg", TOKEN_INSN, C_G, I_CMOVcc },
        { "cmovge", TOKEN_INSN, C_GE, I_CMOVcc },
        { "cmovl", TOKEN_INSN, C_L, I_CMOVcc },
        { "cmovle", TOKEN_INSN, C_LE, I_CMOVcc },
        { "cmovna", TOKEN_INSN, C_NA, I_CMOVcc },
        { "cmovnae", TOKEN_INSN, C_NAE, I_CMOVcc },
        { "cmovnb", TOKEN_INSN, C_NB, I_CMOVcc },
        { "cmovnbe", TOKEN_INSN, C_NBE, I_CMOVcc },
        { "cmovnc", TOKEN_INSN, C_NC, I_CMOVcc },
        { "cmovne", TOKEN_INSN, C_NE, I_CMOVcc },
        { "cmovng", TOKEN_INSN, C_NG, I_CMOVcc },
        { "cmovnge", TOKEN_INSN, C_NGE, I_CMOVcc },
        { "cmovnl", TOKEN_INSN, C_NL, I_CMOVcc },
        { "cmovnle", TOKEN_INSN, C_NLE, I_CMOVcc },
        { "cmovno", TOKEN_INSN, C_NO, I_CMOVcc },
        { "cmovnp", TOKEN_INSN, C_NP, I_CMOVcc },
        { "cmovns", TOKEN_INSN, C_NS, I_CMOVcc },
        { "cmovnz", TOKEN_INSN, C_NZ, I_CMOVcc },
        { "cmovo", TOKEN_INSN, C_O, I_CMOVcc },
        { "cmovp", TOKEN_INSN, C_P, I_CMOVcc },
        { "cmovpe", TOKEN_INSN, C_PE, I_CMOVcc },
        { "cmovpo", TOKEN_INSN, C_PO, I_CMOVcc },
        { "cmovs", TOKEN_INSN, C_S, I_CMOVcc },
        { "cmovz", TOKEN_INSN, C_Z, I_CMOVcc },
        { "ja", TOKEN_INSN, C_A, I_Jcc },
        { "jae", TOKEN_INSN, C_AE, I_Jcc },
        { "jb", TOKEN_INSN, C_B, I_Jcc },
        { "jbe", TOKEN_INSN, C_BE, I_Jcc },
        { "jc", TOKEN_INSN, C_C, I_Jcc },
        { "je", TOKEN_INSN, C_E, I_Jcc },
        { "jg", TOKEN_INSN, C_G, I_Jcc },
        { "jge", TOKEN_INSN, C_GE, I_Jcc },
        { "jl", TOKEN_INSN, C_L, I_Jcc },
        { "jle", TOKEN_INSN, C_LE, I_Jcc },
        { "jna", TOKEN_INSN, C_NA, I_Jcc },
        { "jnae", TOKEN_INSN, C_NAE, I_Jcc },
        { "jnb", TOKEN_INSN, C_NB, I_Jcc },
        { "jnbe", TOKEN_INSN, C_NBE, I_Jcc },
        { "jnc", TOKEN_INSN, C_NC, I_Jcc },
        { "jne", TOKEN_INSN, C_NE, I_Jcc },
        { "jng", TOKEN_INSN, C_NG, I_Jcc },
        { "jnge", TOKEN_INSN, C_NGE, I_Jcc },
        { "jnl", TOKEN_INSN, C_NL, I_Jcc },
        { "jnle", TOKEN_INSN, C_NLE, I_Jcc },
        { "jno", TOKEN_INSN, C_NO, I_Jcc },
        { "jnp", TOKEN_INSN, C_NP, I_Jcc },
        { "jns", TOKEN_INSN, C_NS, I_Jcc },
        { "jnz", TOKEN_INSN, C_NZ, I_Jcc },
        { "jo", TOKEN_INSN, C_O, I_Jcc },
        { "jp", TOKEN_INSN, C_P, I_Jcc },
        { "jpe", TOKEN_INSN, C_PE, I_Jcc },
        { "jpo", TOKEN_INSN, C_PO, I_Jcc },
        { "js", TOKEN_INSN, C_S, I_Jcc },
        { "jz", TOKEN_INSN, C_Z, I_Jcc },
        { "seta", TOKEN_INSN, C_A, I_SETcc },
        { "setae", TOKEN_INSN, C_AE, I_SETcc },
        { "setb", TOKEN_INSN, C_B, I_SETcc },
        { "setbe", TOKEN_INSN, C_BE, I_SETcc },
        { "setc", TOKEN_INSN, C_C, I_SETcc },
        { "sete", TOKEN_INSN, C_E, I_SETcc },
        { "setg", TOKEN_INSN, C_G, I_SETcc },
        { "setge", TOKEN_INSN, C_GE, I_SETcc },
        { "setl", TOKEN_INSN, C_L, I_SETcc },
        { "setle", TOKEN_INSN, C_LE, I_SETcc },
        { "setna", TOKEN_INSN, C_NA, I_SETcc },
        { "setnae", TOKEN_INSN, C_NAE, I_SETcc },
        { "setnb", TOKEN_INSN, C_NB, I_SETcc },
        { "setnbe", TOKEN_INSN, C_NBE, I_SETcc },
        { "setnc", TOKEN_INSN, C_NC, I_SETcc },
        { "setne", TOKEN_INSN, C_NE, I_SETcc },
        { "setng", TOKEN_INSN, C_NG, I_SETcc },
        { "setnge", TOKEN_INSN, C_NGE, I_SETcc },
        { "setnl", TOKEN_INSN, C_NL, I_SETcc },
        { "setnle", TOKEN_INSN, C_NLE, I_SETcc },
        { "setno", TOKEN_INSN, C_NO, I_SETcc },
        { "setnp", TOKEN_INSN, C_NP, I_SETcc },
        { "setns", TOKEN_INSN, C_NS, I_SETcc },
        { "setnz", TOKEN_INSN, C_NZ, I_SETcc },
        { "seto", TOKEN_INSN, C_O, I_SETcc },
        { "setp", TOKEN_INSN, C_P, I_SETcc },
        { "setpe", TOKEN_INSN, C_PE, I_SETcc },
        { "setpo", TOKEN_INSN, C_PO, I_SETcc },
        { "sets", TOKEN_INSN, C_S, I_SETcc },
        { "setz", TOKEN_INSN, C_Z, I_SETcc },



        { "al", TOKEN_REG, 0, R_AL },
        { "ah", TOKEN_REG, 0, R_AH },
        { "ax", TOKEN_REG, 0, R_AX },
        { "eax", TOKEN_REG, 0, R_EAX },
        { "bl", TOKEN_REG, 0, R_BL },
        { "bh", TOKEN_REG, 0, R_BH },
        { "bx", TOKEN_REG, 0, R_BX },
        { "ebx", TOKEN_REG, 0, R_EBX },
        { "cl", TOKEN_REG, 0, R_CL },
        { "ch", TOKEN_REG, 0, R_CH },
        { "cx", TOKEN_REG, 0, R_CX },
        { "ecx", TOKEN_REG, 0, R_ECX },
        { "dl", TOKEN_REG, 0, R_DL },
        { "dh", TOKEN_REG, 0, R_DH },
        { "dx", TOKEN_REG, 0, R_DX },
        { "edx", TOKEN_REG, 0, R_EDX },
        { "sp", TOKEN_REG, 0, R_SP },
        { "esp", TOKEN_REG, 0, R_ESP },
        { "bp", TOKEN_REG, 0, R_BP },
        { "ebp", TOKEN_REG, 0, R_EBP },
        { "si", TOKEN_REG, 0, R_SI },
        { "esi", TOKEN_REG, 0, R_ESI },
        { "di", TOKEN_REG, 0, R_DI },
        { "edi", TOKEN_REG, 0, R_EDI },
        { "cs", TOKEN_REG, 0, R_CS },
        { "ds", TOKEN_REG, 0, R_DS },
        { "es", TOKEN_REG, 0, R_ES },
        { "ss", TOKEN_REG, 0, R_SS },
        { "fs", TOKEN_REG, 0, R_FS },
        { "gs", TOKEN_REG, 0, R_GS },
        { "segr6", TOKEN_REG, 0, R_SEGR6 },
        { "segr7", TOKEN_REG, 0, R_SEGR7 },
        { "cr0", TOKEN_REG, 0, R_CR0 },
        { "cr1", TOKEN_REG, 0, R_CR1 },
        { "cr2", TOKEN_REG, 0, R_CR2 },
        { "cr3", TOKEN_REG, 0, R_CR3 },
        { "cr4", TOKEN_REG, 0, R_CR4 },
        { "cr5", TOKEN_REG, 0, R_CR5 },
        { "cr6", TOKEN_REG, 0, R_CR6 },
        { "cr7", TOKEN_REG, 0, R_CR7 },
        { "cr8", TOKEN_REG, 0, R_CR8 },
        { "cr9", TOKEN_REG, 0, R_CR9 },
        { "cr10", TOKEN_REG, 0, R_CR10 },
        { "cr11", TOKEN_REG, 0, R_CR11 },
        { "cr12", TOKEN_REG, 0, R_CR12 },
        { "cr13", TOKEN_REG, 0, R_CR13 },
        { "cr14", TOKEN_REG, 0, R_CR14 },
        { "cr15", TOKEN_REG, 0, R_CR15 },
        { "dr0", TOKEN_REG, 0, R_DR0 },
        { "dr1", TOKEN_REG, 0, R_DR1 },
        { "dr2", TOKEN_REG, 0, R_DR2 },
        { "dr3", TOKEN_REG, 0, R_DR3 },
        { "dr4", TOKEN_REG, 0, R_DR4 },
        { "dr5", TOKEN_REG, 0, R_DR5 },
        { "dr6", TOKEN_REG, 0, R_DR6 },
        { "dr7", TOKEN_REG, 0, R_DR7 },
        { "dr8", TOKEN_REG, 0, R_DR8 },
        { "dr9", TOKEN_REG, 0, R_DR9 },
        { "dr10", TOKEN_REG, 0, R_DR10 },
        { "dr11", TOKEN_REG, 0, R_DR11 },
        { "dr12", TOKEN_REG, 0, R_DR12 },
        { "dr13", TOKEN_REG, 0, R_DR13 },
        { "dr14", TOKEN_REG, 0, R_DR14 },
        { "dr15", TOKEN_REG, 0, R_DR15 },
        { "tr0", TOKEN_REG, 0, R_TR0 },
        { "tr1", TOKEN_REG, 0, R_TR1 },
        { "tr2", TOKEN_REG, 0, R_TR2 },
        { "tr3", TOKEN_REG, 0, R_TR3 },
        { "tr4", TOKEN_REG, 0, R_TR4 },
        { "tr5", TOKEN_REG, 0, R_TR5 },
        { "tr6", TOKEN_REG, 0, R_TR6 },
        { "tr7", TOKEN_REG, 0, R_TR7 },
        { "st0", TOKEN_REG, 0, R_ST0 },
        { "st1", TOKEN_REG, 0, R_ST1 },
        { "st2", TOKEN_REG, 0, R_ST2 },
        { "st3", TOKEN_REG, 0, R_ST3 },
        { "st4", TOKEN_REG, 0, R_ST4 },
        { "st5", TOKEN_REG, 0, R_ST5 },
        { "st6", TOKEN_REG, 0, R_ST6 },
        { "st7", TOKEN_REG, 0, R_ST7 },
        { "mm0", TOKEN_REG, 0, R_MM0 },
        { "mm1", TOKEN_REG, 0, R_MM1 },
        { "mm2", TOKEN_REG, 0, R_MM2 },
        { "mm3", TOKEN_REG, 0, R_MM3 },
        { "mm4", TOKEN_REG, 0, R_MM4 },
        { "mm5", TOKEN_REG, 0, R_MM5 },
        { "mm6", TOKEN_REG, 0, R_MM6 },
        { "mm7", TOKEN_REG, 0, R_MM7 },
        { "xmm0", TOKEN_REG, 0, R_XMM0 },
        { "xmm1", TOKEN_REG, 0, R_XMM1 },
        { "xmm2", TOKEN_REG, 0, R_XMM2 },
        { "xmm3", TOKEN_REG, 0, R_XMM3 },
        { "xmm4", TOKEN_REG, 0, R_XMM4 },
        { "xmm5", TOKEN_REG, 0, R_XMM5 },
        { "xmm6", TOKEN_REG, 0, R_XMM6 },
        { "xmm7", TOKEN_REG, 0, R_XMM7 },
        { "xmm8", TOKEN_REG, 0, R_XMM8 },
        { "xmm9", TOKEN_REG, 0, R_XMM9 },
        { "xmm10", TOKEN_REG, 0, R_XMM10 },
        { "xmm11", TOKEN_REG, 0, R_XMM11 },
        { "xmm12", TOKEN_REG, 0, R_XMM12 },
        { "xmm13", TOKEN_REG, 0, R_XMM13 },
        { "xmm14", TOKEN_REG, 0, R_XMM14 },
        { "xmm15", TOKEN_REG, 0, R_XMM15 },
        { "ymm0", TOKEN_REG, 0, R_YMM0 },
        { "ymm1", TOKEN_REG, 0, R_YMM1 },
        { "ymm2", TOKEN_REG, 0, R_YMM2 },
        { "ymm3", TOKEN_REG, 0, R_YMM3 },
        { "ymm4", TOKEN_REG, 0, R_YMM4 },
        { "ymm5", TOKEN_REG, 0, R_YMM5 },
        { "ymm6", TOKEN_REG, 0, R_YMM6 },
        { "ymm7", TOKEN_REG, 0, R_YMM7 },
        { "ymm8", TOKEN_REG, 0, R_YMM8 },
        { "ymm9", TOKEN_REG, 0, R_YMM9 },
        { "ymm10", TOKEN_REG, 0, R_YMM10 },
        { "ymm11", TOKEN_REG, 0, R_YMM11 },
        { "ymm12", TOKEN_REG, 0, R_YMM12 },
        { "ymm13", TOKEN_REG, 0, R_YMM13 },
        { "ymm14", TOKEN_REG, 0, R_YMM14 },
        { "ymm15", TOKEN_REG, 0, R_YMM15 },
        { "a16", TOKEN_PREFIX, 0, P_A16 },
        { "a32", TOKEN_PREFIX, 0, P_A32 },
        { "asp", TOKEN_PREFIX, 0, P_ASP },
        { "lock", TOKEN_PREFIX, 0, P_LOCK },
        { "o16", TOKEN_PREFIX, 0, P_O16 },
        { "o32", TOKEN_PREFIX, 0, P_O32 },
        { "osp", TOKEN_PREFIX, 0, P_OSP },
        { "rep", TOKEN_PREFIX, 0, P_REP },
        { "repe", TOKEN_PREFIX, 0, P_REPE },
        { "repne", TOKEN_PREFIX, 0, P_REPNE },
        { "repnz", TOKEN_PREFIX, 0, P_REPNZ },
        { "repz", TOKEN_PREFIX, 0, P_REPZ },
        { "times", TOKEN_PREFIX, 0, P_TIMES },
        { "wait", TOKEN_PREFIX, 0, P_WAIT },
        { "abs", TOKEN_SPECIAL, 0, S_ABS },
        { "byte", TOKEN_SPECIAL, 0, S_BYTE },
        { "dword", TOKEN_SPECIAL, 0, S_DWORD },
        { "far", TOKEN_SPECIAL, 0, S_FAR },
        { "long", TOKEN_SPECIAL, 0, S_LONG },
        { "near", TOKEN_SPECIAL, 0, S_NEAR },
        { "nosplit", TOKEN_SPECIAL, 0, S_NOSPLIT },
        { "oword", TOKEN_SPECIAL, 0, S_OWORD },
        { "qword", TOKEN_SPECIAL, 0, S_QWORD },
        { "rel", TOKEN_SPECIAL, 0, S_REL },
        { "short", TOKEN_SPECIAL, 0, S_SHORT },
        { "strict", TOKEN_SPECIAL, 0, S_STRICT },
        { "to", TOKEN_SPECIAL, 0, S_TO },
        { "tword", TOKEN_SPECIAL, 0, S_TWORD },
        { "word", TOKEN_SPECIAL, 0, S_WORD },
        { "yword", TOKEN_SPECIAL, 0, S_YWORD },
        { "__infinity__", TOKEN_FLOAT, 0, 0 },
        { "__nan__", TOKEN_FLOAT, 0, 0 },
        { "__qnan__", TOKEN_FLOAT, 0, 0 },
        { "__snan__", TOKEN_FLOAT, 0, 0 },
        { "__float8__", TOKEN_FLOATIZE, 0, FLOAT_8 },
        { "__float16__", TOKEN_FLOATIZE, 0, FLOAT_16 },
        { "__float32__", TOKEN_FLOATIZE, 0, FLOAT_32 },
        { "__float64__", TOKEN_FLOATIZE, 0, FLOAT_64 },
        { "__float80m__", TOKEN_FLOATIZE, 0, FLOAT_80M },
        { "__float80e__", TOKEN_FLOATIZE, 0, FLOAT_80E },
        { "__float128l__", TOKEN_FLOATIZE, 0, FLOAT_128L },
        { "__float128h__", TOKEN_FLOATIZE, 0, FLOAT_128H },
        { "__utf16__", TOKEN_STRFUNC, 0, STRFUNC_UTF16 },
        { "__utf32__", TOKEN_STRFUNC, 0, STRFUNC_UTF32 },
        { "seg", TOKEN_SEG, 0, 0 },
        { "wrt", TOKEN_WRT, 0, 0 },
    };
    uint32_t k1, k2;
    uint64_t crc;
    uint16_t ix;
    const struct tokendata *data;

    crc = crc64(UINT64_C(0x13f0eafb407e486a), token);
    k1 = (uint32_t)crc;
    k2 = (uint32_t)(crc >> 32);

    ix = hash1[k1 & 0x7ff] + hash2[k2 & 0x7ff];
    if (ix >= 1732)
        return tv->t_type = TOKEN_ID;

    data = &tokendata[ix];
    if (strcmp(data->string, token))
        return tv->t_type = TOKEN_ID;

    tv->t_integer = data->num;
    tv->t_inttwo  = data->aux;
    return tv->t_type = data->tokentype;
}
