| Generated by c86 (bas) 6.0pre from test.c
c386_compiled.:

    .data
L1:
	.ascii	"Hello World!"
	.byte	0xa,0x0
	.align	2
	.globl	_main
	.text
_main:
	jmp	L2
L3:
	mov	 word ax,  word #13
	push	 word ax
	mov	 word ax,  word #L1
	push	 word ax
	mov	 word ax,  word #1
	push	 word ax
	call	_write
	add	 word sp,  word #6
	xor	 word ax,  word ax
	push	 word ax
	call	_exit
	add	 word sp,  word #2
	mov	 word sp,  word bp
	pop	 word bp
	ret
L2:
	push	 word bp
	mov	 word bp,  word sp
	jmp	L3
	.globl	_write
	.globl	_exit
